with open('data1.csv', 'w') as file:
    file.write('Great', 'Work')
    file.write('0', '3')
    file.write('1', '5')
    file.write('2', '6')
    file.write('3', '7')
    file.write('4', '6')
    file.write('5', '8')
    file.write('6', '11')
    file.write('7', '15')
    file.write('8', '18')
    file.write('9', '20')
