with open('data1.csv', 'w') as file:
    file.write('Great,Work\n')
    file.write('0,3\n')
    file.write('1,5\n')
    file.write('2,6\n')
    file.write('3,7\n')
    file.write('4,6\n')
    file.write('5,8\n')
    file.write('6,11\n')
    file.write('7,15\n')
    file.write('8,18\n')
    file.write('9,20\n')
